name: sakan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.7.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  flutter_secure_storage: ^9.2.2
  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  status_change: ^2.0.0
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  http_parser: ^4.0.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.5
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.7
  firebase_analytics: ^11.3.7
  url_launcher: ^6.2.2
  flutter_local_notifications: ^17.2.4
  package_info_plus: ^8.0.0
  pub_semver: ^2.1.4


dependency_overrides:
  flutter_spinkit: 5.2.1
  win32: ^5.5.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_flavorizr: 2.4.1

flavorizr:
  flavors:
    development:
      app:
        name: "Sakan Provider Dev"
      android:
        applicationId: "com.sakan.service_provider"
      ios:
        bundleId: "com.sakan.service-provider"
        buildSettings:
          PRODUCT_BUNDLE_IDENTIFIER: "com.sakan.service-provider"

    production:
      app:
        name: "Sakan Provider"
      android:
        applicationId: "com.sakan.service_provider"
      ios:
        bundleId: "com.sakan.service-provider"
        buildSettings:
          PRODUCT_BUNDLE_IDENTIFIER: "com.sakan.service-provider"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/sakan-logo.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sakan-logo.png"

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family:  Montserrat-Arabic
    fonts:
      - asset: assets/fonts/Montserrat-Arabic-Black.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Arabic-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-Arabic-ExtraLight.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Arabic-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Arabic-Thin.ttf
        weight: 100

